version: "3"
services:
  web:
    build: .
    command: /bin/sh -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
